import json
import os
import sys
import random

# --- [新增] 导入必要的库 ---
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel

current_file_path = os.path.abspath(__file__)
parent_dir = os.path.dirname(current_file_path)
grandparent_dir = os.path.dirname(os.path.dirname(parent_dir))
sys.path.insert(0, grandparent_dir)

from json_repair import repair_json
from tqdm import tqdm
from utils.Prompt import get_user_messages, get_system_messages_v4_sft, Persuader_First_Sentence
from utils.Prompt import human_persuader_strategy_instruction_map
from utils.api_call import call_llm_chat_api_openai # 假设这个函数保持不变
from utils.retry import retry

# --- 1. [核心修改] 定义全局模型变量 ---
SFT_MODEL = None
SFT_TOKENIZER = None
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# --- 2. [核心修改] 重写 call_api 函数 ---
def call_api(payload: dict):
    """
    一个被修改的 "API" 调用函数。
    它会拦截本地模型的生成任务，并直接处理。
    对于其他任务或模型，它会退回到原始的网络请求逻辑（如果需要的话）。
    """
    global SFT_MODEL, SFT_TOKENIZER, DEVICE

    # a. 检查这是否是我们想要拦截的本地SFT模型任务
    # 在这个脚本中，只有 get_system_response 会调用 call_api
    # 并且 payload['task_type'] 会是 "generate"
    if payload.get("task_type") == "generate" and SFT_MODEL is not None:
        print("拦截到本地SFT模型生成任务，正在直接处理...")

        # b. 从payload中提取messages，并构建Prompt
        # 这里的逻辑需要适配 get_system_messages_v4 的输出
        system_messages = payload["messages"]
        # get_system_messages_v4 返回的列表中，最后一个user message包含了完整的Prompt内容
        prompt = system_messages[-1]['content']

        # c. 使用本地模型进行生成
        inputs = SFT_TOKENIZER(prompt, return_tensors="pt").to(DEVICE)
        with torch.no_grad():
            # with torch.cuda.amp.autocast(dtype=torch.bfloat16):
            #     outputs = SFT_MODEL.generate(
            #         **inputs,
            #         max_new_tokens=128,
            #         num_beams=3,
            #         do_sample=False,
            #         pad_token_id=SFT_TOKENIZER.eos_token_id
            #     )
            with torch.cuda.amp.autocast(dtype=torch.bfloat16):
                outputs = SFT_MODEL.generate(
                    **inputs,
                    max_new_tokens=128,
                    # [核心修改] 从束搜索切换到随机采样
                    do_sample=True,      # 启用采样
                    temperature=0.7,     # 控制随机性（0.7-0.9是不错的起点），值越高越随机
                    top_p=0.9,           # 核采样，只在概率最高的90%的词汇中进行选择，防止生成胡话
                    pad_token_id=SFT_TOKENIZER.eos_token_id
                    # num_beams=3,       # 启用采样时，通常不与 beam search 同时使用
                    )

        response_ids = outputs[0][len(inputs.input_ids[0]):]
        response_text = SFT_TOKENIZER.decode(response_ids, skip_special_tokens=True).strip()

        # d. [关键] 返回一个与原始API格式完全相同的伪响应
        # 我们的 only-response 模型不生成策略，所以我们只填充 response 字段
        # 为了让 get_system_response 函数能正常工作，我们伪造一个空的 "strategy" 和 "reason"
        # get_system_response 期待一个能被 json.loads 解析的字符串
        pseudo_json_string = json.dumps({
            "strategy": "inferred_from_response", # 伪造的策略
            "response": response_text,
            "reason": "Generated by local SFT model." # 伪造的理由
        })

        return {
            "generated_texts": [pseudo_json_string]
        }

    # e. 如果不是我们要拦截的任务，就执行原始的网络请求逻辑
    # 在这个脚本中，这个分支可能不会被执行，但保留下来以保证兼容性
    else:
        API_URL = "http://127.0.0.1:8992/inference"
        headers = {"Content-Type": "application/json"}
        try:
            response = requests.post(API_URL, headers=headers, data=json.dumps(payload))
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            print(f"请求失败: {e}")
            return None

# ... 所有其他函数 (translate_to_lower_keys, get_system_response, run_exp_motivation_0 等) 保持完全不变 ...
def translate_to_lower_keys(input_dict):
    return {k.lower(): v for k, v in input_dict.items()}

# ...
def print_list(history):
    for item in history:
        print(f"{item['role']}: {item['content']}")

def get_assistant_prefix(tokenizer, messages: list) -> str:
    if not messages or messages[-1]['role'] != 'user':
        raise ValueError("The last message in the history must be from the 'user' to get the assistant prefix.")
    prompt_no_assistant = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False,
        enable_thinking=False
    )
    prompt_with_assistant = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=False
    )
    if prompt_with_assistant.startswith(prompt_no_assistant):
        assistant_prefix = prompt_with_assistant[len(prompt_no_assistant):]
        return assistant_prefix
    else:
        # 这种情况很少见，但作为健壮性检查
        raise RuntimeError("Could not determine the assistant prefix. The chat template might be unusual.")

def get_last_assistant_json_template(assitant_content) -> str:
    strategy_marker = '"strategy"'
    index_start = assitant_content.find(strategy_marker)
    if index_start == -1:
        raise ValueError("The assistant content does not contain a 'strategy' field.")
    index_end = index_start + len(strategy_marker)
    json_template = assitant_content[:index_end]
    return json_template

def get_strategy_entropy_correct(conversation_history: list, tokenizer):
    history_prompt = tokenizer.apply_chat_template(
        conversation_history[:-1], # 不要最后一轮模型的回复
        tokenize=False,
        add_generation_prompt=False,
        enable_thinking=False
    )
    assistant_prefix = get_assistant_prefix(tokenizer, conversation_history[:-1])
    incomplete_json_template = get_last_assistant_json_template(assitant_content=conversation_history[-1]['content'])
    text_to_probe = history_prompt + assistant_prefix + incomplete_json_template
    return text_to_probe

def formatted_strateies(strategies):
    return '\n'.join([f"{i+1}. {key}: {value}" for i, (key, value) in enumerate(strategies.items())])

# 加入了历史交互轨迹
def formatted_dialog_history(dialog_history, sys_role, user_role):
    formatted_history = ""
    for turn in dialog_history:
        role = turn['role']
        content = turn['content']
        formatted_history += f"{role.capitalize()}: {content}\n"
    return formatted_history

def formatted_dialog_trajectory(dialog_history):
    results = []
    for idx in range(0, len(dialog_history) - 1, 2):
        sys_utt = dialog_history[idx]
        user_utt = dialog_history[idx+1]
        content = f"""
        Turn: {sys_utt['round']}
        {sys_utt['role']} response: {sys_utt['content']}
        {user_utt['role']} response: {user_utt['content']} 
        """
        # 删除模型的理由，模拟最真实的标注场景
        results.append(content.strip())
    return "\n---\n".join(results)

def AI_judge_prompt(dialog_history, task_info):
    dialog_trajcetory = formatted_dialog_trajectory(dialog_history)
    strategy_content = formatted_strateies(task_info['strategies'])
    messages = [
        {"role": "system", "content": "You are an expert AI judge specializing in evaluating and inferring strategies from dialogue trajectories."},

        {"role": "user", "content": f"""
            ## Role Definition
            You are a top-tier dialogue strategy analyst, skilled at dissecting conversation flow and identifying high-level plans. Your core task is to **infer the underlying dialogue strategies** used by the system in each turn, and **segment the conversation into key stages**.
            
            You will receive a complete dialogue trajectory where the system's previous strategies are NOT explicitly labeled, only the responses.
            
            ## Task Background:
            * Task Description: {task_info['description']}
            * System Role: {task_info['system_role']}
            * User Role: {task_info['user_role']}
            * **Known Strategy Set (Reference):** {strategy_content} own strategies.

            ## Dialogue Trajectory (Strategy NOT Labeled):
            {dialog_trajcetory}
            
            ## Thinking Process:
            1. Global Understanding & Stage Segmentation: First, read the entire dialogue. Segment the conversation into key stages (e.g., Opening, Value Building, Negotiation, etc.).
            2. **Strategy Inference & Attribution:** Analyze each system response sequentially. **For every turn, infer one or more strategies that were used to formulate the response.**
               * **Naming Convention:** Use the exact name from the **Known Strategy Set**. If the strategy is NOT in the set, summarize and name a **New Strategy** (Format: "New Strategy Name: Brief description").
               * **Multi-Strategy Labeling:** If a turn uses multiple strategies, list them sequentially.
            3. Output Generation: Generate your analysis strictly following the specified output format.

            ## Please strictly adhere to the following output format:
            ```
            <thinking_process>
            [Your detailed thought process on flow, user resistance, and key strategic choices.]
            <stage_segmentation_result>
            ```json
            [
                {{
                    "stage idx": 1,
                    "stage name": "XX", 
                    "turns": [X,X],
                    "reasoning": "Briefly explain what dialogue content or strategy shifts led you to define this stage."
                }}
            ]
            ```
            <strategy_inference_result>
            ```json
            [
                {{
                    "turn": 1, 
                    "inferred_strategies": [ // Array to hold one or more strategies
                        {{"strategy_name": "Strategy Name 1", "reasoning": "Basis for Strategy 1 inference."}},
                        {{"strategy_name": "New Strategy: Brief Description", "reasoning": "Basis for Strategy 2 inference."}}
                    ]
                }},
                // ... and so on for all turns
            ]
            ```
            ```
            Attention! You must infer strategies for ALL system turns. Do not miss any turns.
        """}
    ]
    return messages

def parse_llm_output_by_markers(result_text):
    # 定义三个标记
    think_marker = "<thinking_process>"
    segment_marker = "<stage_segmentation_result>"
    judgement_marker = "<strategy_inference_result>"

    # --- 1. 定位每个标记的起始位置 ---
    # .find() 如果找不到会返回 -1
    idx_think = result_text.find(think_marker)
    idx_segment = result_text.find(segment_marker)
    idx_judgement = result_text.find(judgement_marker)

    # --- 2. 检查标记是否存在 ---
    # 如果任何一个关键标记不存在，可能无法正确解析，可以选择返回错误或空字典
    if idx_think == -1 or idx_segment == -1 or idx_judgement == -1:
        print("错误：输出中缺少一个或多个关键标记。")
        raise ValueError(f"输出格式错误 {result_text}")

    # 提取 <thinking_process> 的内容
    # 内容开始于 think_marker 之后，结束于 segment_marker 之前
    start = idx_think + len(think_marker)
    end = idx_segment
    thinking_process_raw = result_text[start:end].strip()

    # 提取 <stage_segmentation_result> 的内容
    # 内容开始于 segment_marker 之后，结束于 judgement_marker 之前
    start = idx_segment + len(segment_marker)
    end = idx_judgement
    stage_segmentation_raw = result_text[start:end].strip()

    # 提取 <strategy_judgment_result> 的内容
    # 内容开始于 judgement_marker 之后，一直到字符串末尾
    start = idx_judgement + len(judgement_marker)
    strategy_judgment_raw = result_text[start:].strip()

    # 将提取出的原始字符串块传入辅助函数进行解析
    stage_segmentation_json = json.loads(repair_json(stage_segmentation_raw))
    strategy_judgment_json = json.loads(repair_json(strategy_judgment_raw))

    return {
        "thinking_process": thinking_process_raw,
        "stage_segmentation_raw": stage_segmentation_raw, # 保留原始字符串块
        "strategy_judgment_raw": strategy_judgment_raw,   # 保留原始字符串块
        "stage_segmentation_json": stage_segmentation_json, # 解析后的JSON对象
        "strategy_judgment_json": strategy_judgment_json  # 解析后的JSON对象
    }

# 这将捕获并重试所有继承自 Exception 的错误（几乎是所有常见的运行时错误）
@retry(max_attempts=5, delay=2, exceptions=(Exception,), backoff=2)
def get_judge_response(dialog_history, task_info):
    messages = AI_judge_prompt(dialog_history, task_info)
    results = call_llm_chat_api_openai(model_name="gpt-4o",messages=messages, temperature=0., n=1, max_tokens=10240)
    # 进行处理
    result = results[0]
    judge_result = parse_llm_output_by_markers(result_text=result)
    return judge_result

def get_system_response(env, chat_history, infos, sys_role, user_role, tokenizer):
    chat_history_content = formatted_dialog_history(chat_history, sys_role, user_role)
    new_infos = {}
    new_infos['strategy_set'] = formatted_strateies(infos['strategies'])
    # 注意: get_system_messages_v4 的输出prompt格式需要和SFT训练时一致
    # 这里我们假设 v4 的输出格式与我们SFT模型训练时的格式是兼容的。
    # 如果不兼容，需要修改 get_system_messages_v4
    system_messages = get_system_messages_v4_sft(env, sys_role, new_infos, chat_history_content)
    print_list(system_messages)

    generation_payload = {
        "task_type": "generate",
        "messages": system_messages,
        "temperature": 0.0,
        "n": 1,
        "max_tokens": 10240,
        "enable_thinking": False
    }
    result = call_api(generation_payload)
    print(f"调用本地(伪)API的结果: {result}")
    if result and "generated_texts" in result:
        response = result["generated_texts"][0].strip()
        # repair_json 在这里仍然有用，以防生成的文本不是完美的JSON字符串
        strategy_result_json = translate_to_lower_keys(json.loads(repair_json(response)))
    else:
        raise ValueError("Failed to get a valid response from the API.")

    return strategy_result_json
# ...
# ... (其他所有函数都保持原样) ...
def get_user_response(env, chat_history, user_profile, sys_role, user_role):
    conversation = [{"role": 'assistant' if item['role']==user_role else "user", "content": item['content']} for item in chat_history]
    infos = {}
    infos['user_profile'] = user_profile
    user_messages = get_user_messages(env, user_role, infos, conversation=conversation)
    print_list(user_messages)
    generation_payload = {
        "model_name": "gpt-4o",
        "messages": user_messages,
        "temperature": 0.,
        "n":1,
        "max_tokens": 1024
    }
    try:
        results = call_llm_chat_api_openai(
            model_name=generation_payload['model_name'],
            messages=generation_payload['messages'],
            temperature=generation_payload['temperature'],
            n=generation_payload['n'],
            max_tokens=generation_payload['max_tokens']
        )
    except Exception as e:
        print(f"发生未知错误: {e}")
    response = results[0]
    return response

def get_reward_response(env, chat_history, user_profile, sys_role, user_role):
    conversation = [{"role": 'assistant' if item['role']==user_role else "user", "content": item['content']} for item in chat_history]
    conversation.append({
        "role": "user",
        "content": f"""
            Would you be willing to donate to Save the Children right now?
            """
    })
    infos = {}
    infos['user_profile'] = user_profile
    user_messages = get_user_messages(env, user_role, infos, conversation=conversation)
    print_list(user_messages)
    generation_payload = {
        "model_name": "gpt-4o",
        "messages": user_messages,
        "temperature": 1.1,
        "n":10,
        "max_tokens": 256
    }
    try:
        results = call_llm_chat_api_openai(
            model_name=generation_payload['model_name'],
            messages=generation_payload['messages'],
            temperature=generation_payload['temperature'],
            n=generation_payload['n'],
            max_tokens=generation_payload['max_tokens']
        )
        # print(results)
        reward = get_reward(results)
    except ValueError as e:
        print(f"捕获到错误: {e}")
    except Exception as e:
        print(f"发生未知错误: {e}")
    return reward

def get_reward(outputs):
    reward = 0
    rewards = []

    for output in outputs:
        if 'yes' in output.lower():
            rewards.append(1)
        else:
            rewards.append(-1)
    if -1 in rewards:
        reward = -1
    else:
        reward = 1
    print(f"Reward: {reward}")
    return reward

def run_exp_motivation_0(input_data_file, output_data_file, tokenizer):
    with open(input_data_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    if isinstance(data, dict):
        new_data = []
        for key, value in data.items():
            item = {}
            item['infos'] = {
                "user_profile": value['description'],
                "user_name": key
            }
            new_data.append(item)
        data = new_data
    random_seed = 42
    random.seed(random_seed)
    data = random.sample(data, 4)
    # data = data[1:]
    print(f"共有{len(data)}个用户数据")
    env = "P4G"
    sys_role = "Persuader"
    user_role = "Persuadee"
    infos = {
        "strategies": human_persuader_strategy_instruction_map
    }

    ## 进行每一个角色的对话
    result_data = []
    max_turn = 10
    for idx, item in tqdm(enumerate(data), total=len(data), desc="Processing User Profiles"):
        item_result = {}

        user_profile = item['infos']['user_profile']
        chat_history = []
        for turn in range(max_turn):
            # 系统进行发言
            if turn == 0:
                sys_utt = {
                    "strategy": "greetings",
                    "content": Persuader_First_Sentence,
                    "role": sys_role,
                    "round": turn + 1
                }
            else:
                sys_result = get_system_response(
                    env=env,
                    chat_history=chat_history,
                    infos=infos,
                    sys_role=sys_role,
                    user_role=user_role, tokenizer=tokenizer
                )
                sys_utt = {
                    "content": sys_result['response'],
                    "reason": sys_result['reason'],
                    "role": sys_role,
                    "round": turn+1,
                }

            chat_history.append(sys_utt)

            user_result = get_user_response(
                env=env,
                chat_history=chat_history,
                user_profile=user_profile,
                sys_role=sys_role,
                user_role=user_role)
            user_utt = {
                "content": user_result,
                "role": user_role,
                "round": turn + 1
            }
            chat_history.append(user_utt)

            ## 评估
            reward = get_reward_response(env, chat_history, user_profile, sys_role, user_role)

            if reward >= 1.0:
                success = True
                result = {
                    "success": success,
                    "turns": turn + 1,
                }
                break
            if turn == max_turn - 1:
                success = False
                result = {
                    "success": success,
                    "turns": max_turn,
                }
                break
        item_result = {
            "infos": {
                "user_id": item['infos']['user_name'],
                "user_profile": user_profile,
                "success": result['success'],
                "reward": reward,
                "turns": result['turns'],
            },
            "trajectory":chat_history
        }
        result_data.append(item_result)

    with open(output_data_file, "w", encoding='utf-8') as f:
        json.dump(result_data, f, indent=4, ensure_ascii=False)

# --- 3. [核心修改] 更新 main 函数以加载本地模型 ---
def main():
    global SFT_MODEL, SFT_TOKENIZER

    input_data_file = r"/root/EvolvingAgent-master/EvolvingAgentTest/user_personas.json"
    output_data_file = r"/root/EvolvingAgent-master/EvolvingAgentTest_wym/model/Motivation/results_sft_local_v2.json"

    # a. 指定基础模型和PEFT适配器的路径
    base_model_path = "/data/pretrained_models/Qwen3-8B"
    # 路径要和你的环境完全匹配
    peft_model_path = "/root/EvolvingAgent-master/EvolvingAgentTest_wym/sft/ppdpp/p4g/Qwen3-8B/response_only/best_checkpoint"

    try:
        print(f"正在从 {base_model_path} 加载基础模型和Tokenizer...")
        # b. 加载基础模型和Tokenizer
        # Tokenizer 从 PEFT 路径加载，因为它可能包含特殊tokens的更新
        SFT_TOKENIZER = AutoTokenizer.from_pretrained(peft_model_path)
        base_model = AutoModelForCausalLM.from_pretrained(
            base_model_path,
            torch_dtype=torch.bfloat16,
            device_map="auto",
            # attn_implementation="flash_attention_2"
        )
        if SFT_TOKENIZER.pad_token is None:
            SFT_TOKENIZER.pad_token = SFT_TOKENIZER.eos_token

        print(f"正在从 {peft_model_path} 加载PEFT适配器...")
        # c. 将PEFT适配器加载到基础模型上
        SFT_MODEL = PeftModel.from_pretrained(base_model, peft_model_path)
        SFT_MODEL.eval()

        print("✅ 微调模型已成功加载并准备就绪。")

    except Exception as e:
        print(f"加载模型时出错: {e}")
        exit()

    # d. 运行实验，注意 tokenizer 参数不再需要传递
    # 因为 get_system_response 内部不再需要它
    run_exp_motivation_0(input_data_file, output_data_file, tokenizer=SFT_TOKENIZER)

if __name__ == "__main__":
    main()